# Generated by Django 5.2.13 on 2026-04-25 12:54

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "doc_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        max_length=40,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_slug",
                                message="Must be 3-40 characters of lowercase alphanumeric or underscore, starting with an alphanumeric character.",
                                regex="^[a-z0-9][a-z0-9_]{2,39}$",
                            )
                        ],
                    ),
                ),
                (
                    "bot_id",
                    models.CharField(
                        max_length=40,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_slug",
                                message="Must be 3-40 characters of lowercase alphanumeric or underscore, starting with an alphanumeric character.",
                                regex="^[a-z0-9][a-z0-9_]{2,39}$",
                            )
                        ],
                    ),
                ),
                ("source_type", models.CharField(max_length=20)),
                ("source_filename", models.CharField(blank=True, max_length=500, null=True)),
                ("source_url", models.TextField(blank=True, null=True)),
                ("content_hash", models.CharField(max_length=80)),
                ("chunk_count", models.IntegerField(default=0)),
                ("item_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("deleted", "Deleted"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("last_refreshed_at", models.DateTimeField(auto_now=True)),
                (
                    "bot_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="tenants.bot",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "bot_id"], name="documents_d_tenant__fddc72_idx"
                    ),
                    models.Index(fields=["status"], name="documents_d_status_07369e_idx"),
                ],
            },
        ),
    ]
