# Generated by Django 5.2.13 on 2026-04-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="raw_payload",
            field=models.JSONField(
                blank=True,
                help_text="Validated upload body as posted by the scraper. Debug aid only — do not read this for ingestion / chunking. Set on create/replace; untouched on no_change.",
                null=True,
            ),
        ),
    ]
