# Generated by Django 5.2.13 on 2026-04-25 12:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "tenant_id",
                    models.CharField(
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_slug",
                                message="Must be 3-40 characters of lowercase alphanumeric or underscore, starting with an alphanumeric character.",
                                regex="^[a-z0-9][a-z0-9_]{2,39}$",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["tenant_id"],
            },
        ),
        migrations.CreateModel(
            name="Bot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "bot_id",
                    models.CharField(
                        max_length=40,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_slug",
                                message="Must be 3-40 characters of lowercase alphanumeric or underscore, starting with an alphanumeric character.",
                                regex="^[a-z0-9][a-z0-9_]{2,39}$",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("collection_name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bots",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["tenant_id", "bot_id"],
                "indexes": [
                    models.Index(fields=["tenant", "bot_id"], name="tenants_bot_tenant__589d0d_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "bot_id"), name="unique_bot_per_tenant"
                    )
                ],
            },
        ),
    ]
